module.exports = {
    saleConfig: {
        snapshotedRate: 1,
        whitelistSaleStartTime: "1745383086",
        whitelistSaleEndTime: "1776893886",
        publicSaleStartTime: "1745383086",
        publicSaleEndTime: "1776893886",
    },
    tiers: [
        { tier: 1,  isWhitelistSale: false, usdPrice: "300",  capPerUser: "5",    allocation: "350"   },
        { tier: 2,  isWhitelistSale: false, usdPrice: "350",  capPerUser: "10",   allocation: "405"   },
        { tier: 3,  isWhitelistSale: false, usdPrice: "400",  capPerUser: "15",   allocation: "500"   },
        { tier: 4,  isWhitelistSale: false, usdPrice: "450",  capPerUser: "20",   allocation: "600"   },
        { tier: 5,  isWhitelistSale: false, usdPrice: "500",  capPerUser: "20",   allocation: "650"   },
        { tier: 6,  isWhitelistSale: false, usdPrice: "550",  capPerUser: "20",   allocation: "700"   },
        { tier: 7,  isWhitelistSale: false, usdPrice: "600",  capPerUser: "20",   allocation: "750"   },
        { tier: 8,  isWhitelistSale: false, usdPrice: "650",  capPerUser: "20",   allocation: "800"   },
        { tier: 9,  isWhitelistSale: false, usdPrice: "700",  capPerUser: "0",    allocation: "900"   },
        { tier: 10, isWhitelistSale: false, usdPrice: "750",  capPerUser: "0",    allocation: "1000"  },
        { tier: 11, isWhitelistSale: false, usdPrice: "800",  capPerUser: "0",    allocation: "1100"  },
        { tier: 12, isWhitelistSale: false, usdPrice: "850",  capPerUser: "0",    allocation: "1050"  },
        { tier: 13, isWhitelistSale: false, usdPrice: "900",  capPerUser: "0",    allocation: "1000"  },
        { tier: 14, isWhitelistSale: false, usdPrice: "950",  capPerUser: "0",    allocation: "1000"  },
        { tier: 15, isWhitelistSale: false, usdPrice: "1000", capPerUser: "0",    allocation: "900"   },
        { tier: 16, isWhitelistSale: false, usdPrice: "1050", capPerUser: "0",    allocation: "800"   },
        { tier: 17, isWhitelistSale: false, usdPrice: "1100", capPerUser: "0",    allocation: "700"   },
        { tier: 18, isWhitelistSale: false, usdPrice: "1150", capPerUser: "0",    allocation: "700"   },
        { tier: 19, isWhitelistSale: false, usdPrice: "1200", capPerUser: "0",    allocation: "700"   },
        { tier: 20, isWhitelistSale: false, usdPrice: "1250", capPerUser: "0",    allocation: "700"   },
        { tier: 21, isWhitelistSale: false, usdPrice: "1300", capPerUser: "0",    allocation: "700"   },
        { tier: 22, isWhitelistSale: false, usdPrice: "1350", capPerUser: "0",    allocation: "700"   },
        { tier: 23, isWhitelistSale: false, usdPrice: "1400", capPerUser: "0",    allocation: "700"   },
        { tier: 24, isWhitelistSale: false, usdPrice: "1450", capPerUser: "0",    allocation: "700"   },
        { tier: 25, isWhitelistSale: false, usdPrice: "1500", capPerUser: "0",    allocation: "700"   },
        { tier: 26, isWhitelistSale: false, usdPrice: "1550", capPerUser: "0",    allocation: "700"   },
        { tier: 27, isWhitelistSale: false, usdPrice: "1600", capPerUser: "0",    allocation: "700"   },
        { tier: 28, isWhitelistSale: false, usdPrice: "1650", capPerUser: "0",    allocation: "700"   },
        { tier: 29, isWhitelistSale: false, usdPrice: "1700", capPerUser: "0",    allocation: "700"   },
        { tier: 30, isWhitelistSale: false, usdPrice: "1750", capPerUser: "0",    allocation: "700"   },

        { tier: 1,  isWhitelistSale: true,  usdPrice: "300",  capPerUser: "1",    allocation: "250"   },
        { tier: 2,  isWhitelistSale: true,  usdPrice: "350",  capPerUser: "1",    allocation: "275"   },
        { tier: 3,  isWhitelistSale: true,  usdPrice: "400",  capPerUser: "1",    allocation: "300"   },
        { tier: 4,  isWhitelistSale: true,  usdPrice: "450",  capPerUser: "1",    allocation: "325"   },
        { tier: 5,  isWhitelistSale: true,  usdPrice: "500",  capPerUser: "1",    allocation: "350"   },
        { tier: 6,  isWhitelistSale: true,  usdPrice: "550",  capPerUser: "1",    allocation: "375"   },
        { tier: 7,  isWhitelistSale: true,  usdPrice: "600",  capPerUser: "1",    allocation: "400"   },
        { tier: 8,  isWhitelistSale: true,  usdPrice: "650",  capPerUser: "1",    allocation: "425"   },
    ]
}